import type { Dictionary } from "./fr";

export const en: Dictionary = {
  meta: {
    title: "MH Group — Web & mobile development agency in Morocco",
    description:
      "MH Group designs and builds fast, beautiful, SEO-ready websites, mobile apps and custom software for ambitious brands in Morocco and worldwide.",
    ogLocale: "en_US",
    tagline: "Web & mobile development agency",
  },
  nav: {
    home: "Home",
    services: "Services",
    work: "Work",
    pricing: "Packages",
    blog: "Blog",
    lab: "Lab",
    about: "About",
    contact: "Contact",
    cities: "Cities",
    cta: "Start a project",
    menu: "Menu",
    close: "Close",
    skip: "Skip to content",
    language: "Language",
    top: "Back to top",
  },
  hero: {
    eyebrow: "Digital development agency · Morocco",
    title: "We code digital experiences that help brands grow.",
    lead: "Websites, mobile apps and custom software — built for performance, search visibility and emotion.",
    primary: "Start a project",
    secondary: "Our services",
    scroll: "Scroll",
    specialty: "What we build:",
  },
  intro: {
    label: "The agency",
    text: "MH Group is a development studio that brings design, technology and strategy together. We turn your ideas into fast, accessible and memorable digital products — from the first prototype to launch, and on to growth.",
    link: "About the agency",
  },
  servicesSection: {
    label: "Services",
    title: "Everything you need to launch and grow your digital product.",
    link: "All services",
    more: "Learn more",
  },
  workSection: {
    label: "Work",
    title: "Selected projects",
    link: "All projects",
    hint: "Keep scrolling",
  },
  process: {
    label: "Process",
    title: "A clear process, from brief to launch.",
    steps: [
      {
        title: "Discovery",
        text: "Workshops, market and user research, measurable goals and a keyword strategy.",
      },
      {
        title: "Design",
        text: "Information architecture, wireframes and custom interfaces, prototyped and approved with you before any code is written.",
      },
      {
        title: "Development",
        text: "Modern, tested, optimised code with performance, accessibility and technical SEO built in from day one.",
      },
      {
        title: "Launch & growth",
        text: "Go-live, analytics, maintenance and continuous iteration to keep improving your results.",
      },
    ],
  },
  why: {
    label: "Why MH Group",
    title: "Websites that get seen, load fast and convert.",
    items: [
      {
        title: "Performance first",
        text: "Green Core Web Vitals: fast loading on mobile, even with rich animation.",
      },
      {
        title: "SEO built in",
        text: "Semantic structure, structured data, sitemaps and optimised content from the very first release.",
      },
      {
        title: "Design that stands out",
        text: "Interaction, motion and 3D for a digital identity your customers remember.",
      },
      {
        title: "A long-term partner",
        text: "One point of contact, from strategy to maintenance, who understands your business.",
      },
    ],
  },
  faq: {
    label: "FAQ",
    title: "Frequently asked questions",
    items: [
      {
        q: "How much does a website cost?",
        a: "Every project is quoted individually based on scope, features and timeline. After a first call, we send you a detailed, transparent proposal.",
      },
      {
        q: "How long does it take to build a website?",
        a: "A showcase site usually takes a few weeks; a custom platform or app takes longer. We set a precise schedule at kickoff.",
      },
      {
        q: "Will my website rank well on Google?",
        a: "Technical SEO is part of every project: performance, semantic markup, structured data, sitemaps, multilingual tags and content optimised for your keywords.",
      },
      {
        q: "Do you work with clients outside Morocco?",
        a: "Yes. We work remotely, in French, English and Arabic, with clients in Morocco and around the world.",
      },
      {
        q: "Do you offer maintenance after launch?",
        a: "Yes. We offer post-launch support: updates, security, hosting, new features and performance monitoring.",
      },
    ],
  },
  cta: {
    label: "Have a project in mind?",
    title: "Let's talk.",
    button: "Start a project",
    or: "or email us at",
  },
  footer: {
    tagline: "Web & mobile development agency based in Morocco.",
    navigation: "Navigation",
    services: "Services",
    cities: "Cities",
    allCities: "All of Morocco",
    contact: "Contact",
    legal: "Legal notice",
    privacy: "Privacy",
    follow: "Follow us",
    rights: "All rights reserved.",
    made: "Designed and built in Morocco.",
    top: "Back to top",
  },
  servicesPage: {
    metaTitle: "Services — web, mobile, e-commerce & SEO development",
    metaDescription:
      "Websites, mobile apps, e-commerce, custom software, UI/UX and SEO: explore the services of MH Group, a digital agency in Morocco.",
    label: "Services",
    h1: "Custom digital solutions, from idea to growth.",
    lead: "Strategy, design, development and SEO: one team to design, launch and evolve your digital products.",
  },
  serviceDetail: {
    deliverables: "What we deliver",
    stack: "Technologies",
    faq: "Frequently asked questions",
    others: "Other services",
    cta: "Discuss your project",
    process: "Our process",
  },
  workDetail: {
    challenge: "The challenge",
    solution: "Our solution",
    features: "Key features",
    services: "Services",
    stack: "Technologies",
    client: "Client",
    visit: "Visit the live site",
    next: "Next project",
    all: "All projects",
    view: "View",
  },
  workPage: {
    metaTitle: "Work — web, mobile and software projects",
    metaDescription:
      "Explore a selection of websites, apps and platforms designed and developed by MH Group, a development agency in Morocco.",
    label: "Work",
    h1: "Digital products built to last.",
    lead: "A selection of websites, apps and platforms we have imagined, designed and developed.",
    visit: "Visit site",
  },
  aboutPage: {
    metaTitle: "About — digital development studio in Morocco",
    metaDescription:
      "MH Group is a digital development agency in Morocco bringing design, technology and strategy together to build high-performing web and mobile products.",
    label: "About",
    h1: "A digital studio born in Morocco, built for the world.",
    lead: "We believe a successful digital product is beautiful, fast and useful all at once. That's why designers and developers work side by side from day one to launch — and beyond.",
    missionLabel: "Our mission",
    mission:
      "Help ambitious businesses stand out online with digital products that meet the best international standards: fast, accessible, easy to find and a pleasure to use.",
    valuesLabel: "Our values",
    values: [
      { title: "Craft", text: "Every detail matters, from the pixel to the millisecond of load time." },
      { title: "Transparency", text: "Clear quotes, realistic schedules and honest communication." },
      { title: "Curiosity", text: "We follow the latest technology to recommend the right tools, not the trendiest ones." },
      { title: "Impact", text: "We measure our work by your results: traffic, conversions and happy users." },
    ],
  },
  contactPage: {
    metaTitle: "Contact — let's start your digital project",
    metaDescription:
      "Contact MH Group about your website, mobile app, e-commerce or custom software project. Personal reply and free estimate.",
    label: "Contact",
    h1: "Let's talk about your project.",
    lead: "Tell us about your goals: we'll come back with ideas, a timeline and an estimate.",
    form: {
      name: "Full name",
      email: "Email",
      company: "Company (optional)",
      service: "Service",
      servicePlaceholder: "Choose a service",
      other: "Other",
      budget: "Estimated budget",
      budgetPlaceholder: "Choose a range",
      budgets: ["Under 10,000 MAD", "10,000 – 30,000 MAD", "30,000 – 80,000 MAD", "Over 80,000 MAD", "Not sure yet"],
      message: "Your project",
      messagePlaceholder: "Goals, features, timeline, sites you like…",
      package: "Package",
      submit: "Send message",
      sending: "Sending…",
      note: "Your details are only used to reply to you.",
      privacy: "Privacy policy",
      subject: "New project",
      successTitle: "Message sent!",
      successText: "Thank you — we'll get back to you very soon.",
      again: "Send another message",
      error: "Sending failed. Please try again or email us directly at",
      fallback: "Your email app will open with the message pre-filled.",
    },
    info: {
      email: "Email",
      whatsapp: "WhatsApp",
      location: "Location",
      locationValue: "Morocco — working remotely worldwide",
    },
  },
  sound: {
    on: "Mute the music",
    off: "Turn on the music",
  },
  lab: {
    metaTitle: "Lab — interactive WebGL experiments",
    metaDescription:
      "MH Group's lab: real-time interactive WebGL experiments — liquid, particles, glass. Move your mouse or touch the screen.",
    label: "Lab",
    h1: "The lab. We experiment, you play.",
    lead: "Hand-coded, real-time interactive experiments that show what the web can do. Move your mouse or touch the screen.",
    hint: "Interact",
    play: { on: "Play the animation", off: "Pause" },
    experiments: [
      { id: "liquid", title: "Liquid trail", text: "Metaballs follow your cursor and merge like mercury." },
      { id: "particles", title: "Particles", text: "Thousands of particles draw our logo. Bring your cursor close, then click." },
      { id: "glass", title: "Glass", text: "A glass sphere bends light with chromatic dispersion. Move it around." },
    ],
    cta: "Have an interactive project in mind?",
  },
  studio: {
    showreel: "Watch the showreel",
    close: "Close",
    teamLabel: "The team",
    teamTitle: "The people behind your projects.",
    statsLabel: "In numbers",
  },
  whatsapp: {
    label: "Chat on WhatsApp",
    message: "Hello MH Group, I'd like to discuss a project.",
  },
  pricingPage: {
    metaTitle: "Packages — showcase, business and custom projects",
    metaDescription:
      "Explore MH Group's packages: showcase website, business website and custom projects. Every project gets a free, no-obligation quote.",
    label: "Packages",
    h1: "Three packages, one tailored quote.",
    lead: "Every business is different, so we price each project around your goals. Pick the package that fits you best and we'll send a detailed, free, no-obligation proposal.",
    price: "On quote",
    priceNote: "Free, no-obligation quote",
    popular: "Most popular",
    cta: "Request a quote",
    plans: [
      {
        id: "vitrine",
        name: "Showcase",
        tagline: "Present your business and get found on Google.",
        features: [
          "Up to 5 custom pages",
          "Responsive design: mobile, tablet, desktop",
          "Technical SEO and Google Business Profile",
          "Contact form and WhatsApp button",
          "Launch, domain name and HTTPS",
          "Hand-over and training",
        ],
      },
      {
        id: "business",
        name: "Business",
        tagline: "For companies that want to generate leads every month.",
        features: [
          "Unlimited pages and built-in blog",
          "Premium design and animation",
          "Advanced SEO: keywords, content, structured data",
          "Multilingual site: French, English, Arabic",
          "CMS to edit your content yourself",
          "Analytics and lead tracking",
          "Post-launch support",
        ],
      },
      {
        id: "sur-mesure",
        name: "Custom",
        tagline: "For ambitious apps, platforms and online stores.",
        features: [
          "Web or mobile app, SaaS, e-commerce",
          "Discovery workshops and interactive prototype",
          "Custom architecture and back-end",
          "Integrations: payments, CRM, ERP, APIs",
          "3D and WebGL experiences",
          "Ongoing maintenance and improvements",
        ],
      },
    ],
    includedTitle: "Included in every package",
    included: [
      "Modern, fast and secure code",
      "Technical SEO optimisation",
      "Design tailored to your brand",
      "A single point of contact",
      "You own your website and content",
      "Advice on your online presence",
    ],
    faq: [
      {
        q: "Why are your prices on quote?",
        a: "No two projects are alike: number of pages, features, content, timeline… A tailored quote means you only pay for what you actually need.",
      },
      {
        q: "Is the quote free?",
        a: "Yes, the quote is free and comes with no obligation. After a first conversation about your goals, we send you a detailed proposal.",
      },
      {
        q: "How does payment work?",
        a: "Terms (deposit, milestones, balance) are set out in the quote and adapted to the size of the project.",
      },
      {
        q: "Can I upgrade later?",
        a: "Of course. Your site is built to grow: you can add pages, a blog, a store or new languages at any time.",
      },
    ],
  },
  blog: {
    metaTitle: "Blog — web, mobile and SEO advice in Morocco",
    metaDescription:
      "Advice, guides and best practices on building websites and mobile apps and on SEO in Morocco, from the MH Group team.",
    label: "Blog",
    h1: "Advice and guides to succeed online.",
    lead: "Websites, apps and SEO: practical advice for businesses in Morocco.",
    readMore: "Read article",
    minutes: "min read",
    published: "Published",
    updated: "Updated",
    empty: "Our first articles in this language are coming soon.",
    otherLanguages: "Articles available in other languages",
    back: "All articles",
    related: "Keep reading",
    latestLabel: "Blog",
    latestTitle: "Our latest advice to succeed online.",
    all: "All articles",
  },
  trust: {
    testimonialsLabel: "Testimonials",
    testimonialsTitle: "What our clients say.",
    clientsLabel: "They trusted us",
  },
  cities: {
    metaTitle: "Web agency in Morocco — websites in every city",
    metaDescription:
      "Web agency in Morocco: websites, mobile apps and SEO in Casablanca, Rabat, Marrakech, Tangier, Fez, Agadir, Laayoune, Dakhla and across the country.",
    label: "Morocco",
    h1: "A web agency for all of Morocco.",
    lead: "From Tangier to Dakhla, we work with businesses in every city in the country: one point of contact, video calls, phone or WhatsApp, and websites built for local search.",
    listTitle: "Choose your city",
    notListed: "Your city isn't listed? We work with businesses all over Morocco.",
    city: {
      metaTitle: "Web design & development in {city} — web agency & SEO",
      metaDescription:
        "Web agency in {city}: websites, e-commerce, mobile apps and local SEO for businesses in {city} and the {region} region.",
      label: "Web agency · {city}",
      h1: "Web design and development in {city}",
      lead: "Showcase websites, e-commerce, mobile apps and local SEO for businesses in {city} and the {region} region.",
      sectorsTitle: "Industries we work with in {city}",
      servicesTitle: "Our services in {city}",
      faqTitle: "Frequently asked questions — {city}",
      otherCities: "Other cities",
      cta: "Talk about your project",
      faq: [
        {
          q: "Do you work remotely with businesses in {city}?",
          a: "Yes. We work with businesses all over Morocco by video call, phone and WhatsApp, with one point of contact from the first call to launch.",
        },
        {
          q: "How can I make my {city} business more visible on Google?",
          a: "By combining a fast, well-structured website, local pages, an optimised Google Business Profile and regular customer reviews. We put these levers in place for you.",
        },
      ],
    },
  },
  legal: {
    metaTitle: "Legal notice",
    metaDescription: "Legal notice for the MH Group website: publisher, hosting, intellectual property and liability.",
    label: "Legal information",
    h1: "Legal notice",
    updated: "Last updated",
    toComplete: "To be completed",
    sections: {
      publisher: "Website publisher",
      publisherLines: ["Company name", "Legal form", "Address", "ICE", "RC", "Publication director", "Email"],
      hosting: "Hosting",
      hostingText: "This website is hosted by Vercel Inc., 440 N Barranca Ave #4133, Covina, CA 91723, United States — vercel.com.",
      ip: "Intellectual property",
      ipText: "All content on this website (text, visuals, logo, code) belongs to {name} unless stated otherwise. Any reproduction without prior written permission is prohibited.",
      liability: "Liability",
      liabilityText: "{name} strives to provide accurate, up-to-date information but cannot guarantee it is error-free. Links to third-party websites are not its responsibility.",
      data: "Personal data",
      dataText: "How we process your personal data is described in our privacy policy.",
    },
  },
  privacy: {
    metaTitle: "Privacy policy",
    metaDescription:
      "How MH Group collects and protects your personal data, in line with Moroccan Law 09-08 on the protection of personal data.",
    label: "Legal information",
    h1: "Privacy policy",
    intro:
      "{name} takes the protection of your personal data seriously. This policy explains what data we collect, why, and what your rights are, in line with Moroccan Law No. 09-08 on the protection of individuals with regard to the processing of personal data.",
    sections: [
      {
        title: "Data we collect",
        text: "When you use the contact form or email us, we collect the information you send: name, email address, company, service of interest, indicative budget and message.",
      },
      {
        title: "Purpose",
        text: "This data is only used to answer your request, prepare a quote and manage our business relationship. It is never sold or shared with third parties.",
      },
      {
        title: "Audience measurement",
        text: "We use Vercel Web Analytics to measure traffic in an aggregated, anonymous way. It sets no cookies and cannot identify you.",
      },
      {
        title: "Recipients and hosting",
        text: "Data is processed by {name} and by our technical providers only as needed to run the service: website hosting (Vercel) and sending contact-form emails.",
      },
      {
        title: "Retention",
        text: "Contact requests are kept for as long as needed to handle your request and, where relevant, for the duration of our business relationship.",
      },
      {
        title: "Your rights",
        text: "You have the right to access, correct and object to the processing of your data. To exercise these rights, email us at {email}. You can also lodge a complaint with the CNDP (Morocco's data protection authority) — cndp.ma.",
      },
    ],
  },
  notFound: {
    title: "Page not found",
    text: "The page you are looking for doesn't exist or has moved.",
    back: "Back to home",
    hint: "Hold the click to jump to hyperspace.",
  },
};
