export const fr = {
  meta: {
    title: "MH Group — Agence de développement web & mobile au Maroc",
    description:
      "MH Group conçoit des sites web, applications mobiles et logiciels sur-mesure rapides, beaux et optimisés SEO pour les marques ambitieuses au Maroc et à l'international.",
    ogLocale: "fr_MA",
    tagline: "Agence de développement web & mobile",
  },
  nav: {
    home: "Accueil",
    services: "Services",
    work: "Réalisations",
    pricing: "Offres",
    blog: "Blog",
    lab: "Lab",
    about: "Agence",
    contact: "Contact",
    cities: "Villes",
    cta: "Démarrer un projet",
    menu: "Menu",
    close: "Fermer",
    skip: "Aller au contenu",
    language: "Langue",
  },
  hero: {
    eyebrow: "Agence de développement digital · Maroc",
    title: "Nous codons des expériences digitales qui font grandir les marques.",
    lead: "Sites web, applications mobiles et logiciels sur-mesure — pensés pour la performance, le référencement et l'émotion.",
    primary: "Démarrer un projet",
    secondary: "Nos services",
    scroll: "Défiler",
  },
  intro: {
    label: "L'agence",
    text: "MH Group est un studio de développement qui réunit design, technologie et stratégie. Nous transformons vos idées en produits digitaux rapides, accessibles et mémorables — du premier prototype au lancement, puis à la croissance.",
    link: "Découvrir l'agence",
  },
  servicesSection: {
    label: "Services",
    title: "Tout ce qu'il faut pour lancer et faire grandir votre produit digital.",
    link: "Tous les services",
    more: "En savoir plus",
  },
  workSection: {
    label: "Réalisations",
    title: "Projets sélectionnés",
    link: "Toutes les réalisations",
  },
  process: {
    label: "Méthode",
    title: "Un processus clair, du brief au lancement.",
    steps: [
      {
        title: "Découverte",
        text: "Ateliers, analyse de votre marché et de vos utilisateurs, objectifs mesurables et stratégie de mots-clés.",
      },
      {
        title: "Design",
        text: "Architecture, wireframes et interfaces sur-mesure, prototypés et validés avec vous avant la première ligne de code.",
      },
      {
        title: "Développement",
        text: "Code moderne, testé et optimisé : performance, accessibilité et SEO technique intégrés dès le départ.",
      },
      {
        title: "Lancement & croissance",
        text: "Mise en ligne, suivi analytique, maintenance et itérations continues pour faire progresser vos résultats.",
      },
    ],
  },
  why: {
    label: "Pourquoi MH Group",
    title: "Des sites qui se voient, se chargent vite et convertissent.",
    items: [
      {
        title: "Performance d'abord",
        text: "Des Core Web Vitals au vert : chargement rapide sur mobile, même avec des animations riches.",
      },
      {
        title: "SEO intégré",
        text: "Structure sémantique, données structurées, sitemap et contenus optimisés dès la première version.",
      },
      {
        title: "Design qui marque",
        text: "Interactions, motion et 3D pour une identité digitale que vos clients retiennent.",
      },
      {
        title: "Partenaire durable",
        text: "Un interlocuteur unique, du conseil à la maintenance, qui comprend votre activité.",
      },
    ],
  },
  faq: {
    label: "FAQ",
    title: "Questions fréquentes",
    items: [
      {
        q: "Combien coûte la création d'un site web ?",
        a: "Chaque projet est chiffré sur-mesure selon le périmètre, les fonctionnalités et les délais. Après un premier échange, nous vous envoyons une proposition détaillée et transparente.",
      },
      {
        q: "Combien de temps faut-il pour créer un site ?",
        a: "Un site vitrine prend généralement quelques semaines ; une plateforme ou une application sur-mesure demande davantage. Nous fixons un planning précis dès le lancement du projet.",
      },
      {
        q: "Mon site sera-t-il bien référencé sur Google ?",
        a: "Le SEO technique fait partie de chaque projet : performance, balisage sémantique, données structurées, sitemap, balises multilingues et contenus optimisés pour vos mots-clés.",
      },
      {
        q: "Travaillez-vous avec des clients hors du Maroc ?",
        a: "Oui. Nous travaillons à distance, en français, en anglais et en arabe, avec des clients au Maroc et à l'international.",
      },
      {
        q: "Proposez-vous la maintenance après la mise en ligne ?",
        a: "Oui, nous proposons un accompagnement après le lancement : mises à jour, sécurité, hébergement, évolutions et suivi des performances.",
      },
    ],
  },
  cta: {
    label: "Un projet en tête ?",
    title: "Parlons-en.",
    button: "Démarrer un projet",
    or: "ou écrivez-nous à",
  },
  footer: {
    tagline: "Agence de développement web & mobile basée au Maroc.",
    navigation: "Navigation",
    services: "Services",
    cities: "Villes",
    allCities: "Tout le Maroc",
    contact: "Contact",
    legal: "Mentions légales",
    privacy: "Confidentialité",
    follow: "Suivez-nous",
    rights: "Tous droits réservés.",
    made: "Conçu et développé au Maroc.",
    top: "Haut de page",
  },
  servicesPage: {
    metaTitle: "Services — développement web, mobile, e-commerce & SEO",
    metaDescription:
      "Création de sites web, applications mobiles, e-commerce, logiciels sur-mesure, UI/UX et SEO : découvrez les services de MH Group, agence digitale au Maroc.",
    label: "Services",
    h1: "Des solutions digitales sur-mesure, de l'idée à la croissance.",
    lead: "Stratégie, design, développement et référencement : une seule équipe pour concevoir, lancer et faire évoluer vos produits digitaux.",
  },
  serviceDetail: {
    deliverables: "Ce que nous livrons",
    stack: "Technologies",
    faq: "Questions fréquentes",
    others: "Autres services",
    cta: "Discuter de votre projet",
    process: "Notre méthode",
  },
  workDetail: {
    challenge: "Le défi",
    solution: "Notre solution",
    features: "Fonctionnalités clés",
    services: "Services",
    stack: "Technologies",
    client: "Client",
    visit: "Voir le site en ligne",
    next: "Projet suivant",
    all: "Toutes les réalisations",
    view: "Voir",
  },
  workPage: {
    metaTitle: "Réalisations — projets web, mobile et logiciels",
    metaDescription:
      "Découvrez une sélection de sites web, applications et plateformes conçus et développés par MH Group, agence de développement au Maroc.",
    label: "Réalisations",
    h1: "Des produits digitaux conçus pour durer.",
    lead: "Une sélection de sites, applications et plateformes que nous avons imaginés, conçus et développés.",
    visit: "Voir le site",
  },
  aboutPage: {
    metaTitle: "L'agence — studio de développement digital au Maroc",
    metaDescription:
      "MH Group est une agence de développement digital au Maroc qui réunit design, technologie et stratégie pour créer des produits web et mobiles performants.",
    label: "L'agence",
    h1: "Un studio digital né au Maroc, pensé pour le monde.",
    lead: "Nous croyons qu'un produit digital réussi est à la fois beau, rapide et utile. C'est pourquoi designers et développeurs travaillent ensemble du premier jour jusqu'au lancement — et au-delà.",
    missionLabel: "Notre mission",
    mission:
      "Aider les entreprises ambitieuses à exister en ligne avec des produits digitaux à la hauteur des meilleurs standards internationaux : performants, accessibles, bien référencés et agréables à utiliser.",
    valuesLabel: "Nos valeurs",
    values: [
      { title: "Exigence", text: "Chaque détail compte : du pixel à la milliseconde de chargement." },
      { title: "Transparence", text: "Des devis clairs, des plannings réalistes et une communication honnête." },
      { title: "Curiosité", text: "Nous suivons les dernières technologies pour vous proposer les bonnes, pas les plus à la mode." },
      { title: "Impact", text: "Nous mesurons notre travail à vos résultats : trafic, conversions et satisfaction de vos utilisateurs." },
    ],
  },
  contactPage: {
    metaTitle: "Contact — démarrons votre projet digital",
    metaDescription:
      "Contactez MH Group pour votre projet de site web, application mobile, e-commerce ou logiciel sur-mesure. Réponse personnalisée et estimation gratuite.",
    label: "Contact",
    h1: "Parlons de votre projet.",
    lead: "Parlez-nous de vos objectifs : nous revenons vers vous avec des idées, un planning et une estimation.",
    form: {
      name: "Nom complet",
      email: "E-mail",
      company: "Entreprise (optionnel)",
      service: "Service souhaité",
      servicePlaceholder: "Choisir un service",
      other: "Autre",
      budget: "Budget estimé",
      budgetPlaceholder: "Choisir une fourchette",
      budgets: ["Moins de 10 000 MAD", "10 000 – 30 000 MAD", "30 000 – 80 000 MAD", "Plus de 80 000 MAD", "Je ne sais pas encore"],
      message: "Votre projet",
      messagePlaceholder: "Objectifs, fonctionnalités, délais, exemples de sites que vous aimez…",
      package: "Offre",
      submit: "Envoyer le message",
      sending: "Envoi en cours…",
      note: "Vos informations servent uniquement à vous répondre.",
      privacy: "Politique de confidentialité",
      subject: "Nouveau projet",
      successTitle: "Message envoyé !",
      successText: "Merci, nous revenons vers vous très vite.",
      again: "Envoyer un autre message",
      error: "L'envoi a échoué. Réessayez ou écrivez-nous directement à",
      fallback: "Votre messagerie va s'ouvrir avec le message pré-rempli.",
    },
    info: {
      email: "E-mail",
      whatsapp: "WhatsApp",
      location: "Localisation",
      locationValue: "Maroc — nous travaillons à distance partout dans le monde",
    },
  },
  lab: {
    metaTitle: "Lab — expériences interactives WebGL",
    metaDescription:
      "Le laboratoire de MH Group : expériences interactives en WebGL et en temps réel — liquide, particules, verre. Bougez la souris ou touchez l'écran.",
    label: "Lab",
    h1: "Le laboratoire. On expérimente, vous jouez.",
    lead: "Des expériences interactives en temps réel, codées à la main, qui montrent ce que le web peut faire. Bougez la souris ou touchez l'écran.",
    hint: "Interagissez",
    experiments: [
      { id: "liquid", title: "Trace liquide", text: "Des métaballes suivent votre curseur et fusionnent comme du mercure." },
      { id: "particles", title: "Particules", text: "Des milliers de particules dessinent notre logo. Approchez le curseur, puis cliquez." },
      { id: "glass", title: "Verre", text: "Une sphère de verre réfracte la lumière avec une dispersion chromatique. Déplacez-la." },
    ],
    cta: "Un projet interactif en tête ?",
  },
  studio: {
    showreel: "Voir le showreel",
    close: "Fermer",
    teamLabel: "L'équipe",
    teamTitle: "Les personnes derrière vos projets.",
    statsLabel: "En chiffres",
  },
  whatsapp: {
    label: "Discuter sur WhatsApp",
    message: "Bonjour MH Group, j'aimerais discuter d'un projet.",
  },
  pricingPage: {
    metaTitle: "Offres — site vitrine, business et projets sur-mesure",
    metaDescription:
      "Découvrez les offres de MH Group : site vitrine, site business et projets sur-mesure. Chaque projet est chiffré sur devis, gratuitement et sans engagement.",
    label: "Offres",
    h1: "Trois formules, un devis sur-mesure.",
    lead: "Chaque entreprise est unique : nous chiffrons chaque projet selon vos objectifs. Choisissez la formule qui vous ressemble, nous vous envoyons une proposition détaillée, gratuite et sans engagement.",
    price: "Sur devis",
    priceNote: "Devis gratuit et sans engagement",
    popular: "Le plus demandé",
    cta: "Demander un devis",
    plans: [
      {
        id: "vitrine",
        name: "Site vitrine",
        tagline: "Pour présenter votre activité et être trouvé sur Google.",
        features: [
          "Jusqu'à 5 pages sur-mesure",
          "Design responsive : mobile, tablette, ordinateur",
          "SEO technique et fiche Google Business Profile",
          "Formulaire de contact et bouton WhatsApp",
          "Mise en ligne, nom de domaine et HTTPS",
          "Prise en main de votre site",
        ],
      },
      {
        id: "business",
        name: "Business",
        tagline: "Pour les entreprises qui veulent générer des demandes chaque mois.",
        features: [
          "Pages illimitées et blog intégré",
          "Design premium et animations",
          "SEO avancé : mots-clés, contenus, données structurées",
          "Site multilingue : français, anglais, arabe",
          "CMS pour modifier vos contenus en autonomie",
          "Statistiques et suivi des demandes",
          "Accompagnement après le lancement",
        ],
      },
      {
        id: "sur-mesure",
        name: "Sur-mesure",
        tagline: "Pour les applications, plateformes et e-commerces ambitieux.",
        features: [
          "Application web ou mobile, SaaS, e-commerce",
          "Ateliers de cadrage et prototype interactif",
          "Architecture et back-end sur-mesure",
          "Intégrations : paiement, CRM, ERP, API",
          "Expériences 3D et WebGL",
          "Maintenance et évolutions continues",
        ],
      },
    ],
    includedTitle: "Inclus dans toutes les offres",
    included: [
      "Code moderne, rapide et sécurisé",
      "Optimisation SEO technique",
      "Design adapté à votre marque",
      "Un interlocuteur unique",
      "Vous êtes propriétaire de votre site et de vos contenus",
      "Conseils pour votre présence en ligne",
    ],
    faq: [
      {
        q: "Pourquoi vos prix sont-ils sur devis ?",
        a: "Deux projets ne se ressemblent jamais : nombre de pages, fonctionnalités, contenus, délais… Un devis personnalisé vous garantit de payer uniquement ce dont vous avez besoin.",
      },
      {
        q: "Le devis est-il gratuit ?",
        a: "Oui, le devis est gratuit et sans engagement. Après un premier échange sur vos objectifs, nous vous envoyons une proposition détaillée.",
      },
      {
        q: "Comment se déroule le paiement ?",
        a: "Les modalités (acompte, étapes, solde) sont précisées dans le devis et adaptées à la taille du projet.",
      },
      {
        q: "Puis-je faire évoluer mon offre plus tard ?",
        a: "Bien sûr. Votre site est conçu pour évoluer : vous pouvez ajouter des pages, un blog, une boutique ou de nouvelles langues à tout moment.",
      },
    ],
  },
  blog: {
    metaTitle: "Blog — conseils web, mobile et SEO au Maroc",
    metaDescription:
      "Conseils, guides et bonnes pratiques sur la création de sites web, d'applications mobiles et le référencement au Maroc, par l'équipe MH Group.",
    label: "Blog",
    h1: "Conseils et guides pour réussir en ligne.",
    lead: "Création de sites, applications, SEO : nos conseils pratiques pour les entreprises au Maroc.",
    readMore: "Lire l'article",
    minutes: "min de lecture",
    published: "Publié le",
    updated: "Mis à jour le",
    empty: "Nos premiers articles dans cette langue arrivent bientôt.",
    otherLanguages: "Articles disponibles dans d'autres langues",
    back: "Tous les articles",
    related: "À lire aussi",
    latestLabel: "Blog",
    latestTitle: "Nos derniers conseils pour réussir en ligne.",
    all: "Tous les articles",
  },
  trust: {
    testimonialsLabel: "Témoignages",
    testimonialsTitle: "Ce que disent nos clients.",
    clientsLabel: "Ils nous ont fait confiance",
  },
  cities: {
    metaTitle: "Agence web au Maroc — création de sites dans toutes les villes",
    metaDescription:
      "Agence web au Maroc : création de sites, applications mobiles et SEO à Casablanca, Rabat, Marrakech, Tanger, Fès, Agadir, Laâyoune, Dakhla et dans tout le Royaume.",
    label: "Maroc",
    h1: "Une agence web pour tout le Maroc.",
    lead: "De Tanger à Dakhla, nous accompagnons les entreprises de toutes les villes du Royaume : un interlocuteur unique, des échanges en visio, par téléphone ou WhatsApp, et des sites pensés pour le référencement local.",
    listTitle: "Choisissez votre ville",
    notListed: "Votre ville n'est pas dans la liste ? Nous travaillons avec des entreprises partout au Maroc.",
    city: {
      metaTitle: "Création de site web à {city} — agence web & SEO",
      metaDescription:
        "Agence web à {city} : création de sites internet, e-commerce, applications mobiles et SEO local pour les entreprises de {city} et de la région {region}.",
      label: "Agence web · {city}",
      h1: "Création de site web à {city}",
      lead: "Sites vitrines, e-commerce, applications mobiles et référencement local pour les entreprises de {city} et de la région {region}.",
      sectorsTitle: "Les secteurs que nous accompagnons à {city}",
      servicesTitle: "Nos services à {city}",
      faqTitle: "Questions fréquentes — {city}",
      otherCities: "Autres villes",
      cta: "Parler de votre projet",
      faq: [
        {
          q: "Travaillez-vous avec des entreprises de {city} à distance ?",
          a: "Oui. Nous travaillons avec des entreprises de tout le Maroc : visio, téléphone et WhatsApp, avec un interlocuteur unique du premier échange jusqu'à la mise en ligne.",
        },
        {
          q: "Comment améliorer la visibilité de mon entreprise à {city} sur Google ?",
          a: "En combinant un site rapide et bien structuré, des pages locales, une fiche Google Business Profile optimisée et des avis clients réguliers. Nous mettons en place ces leviers pour vous.",
        },
      ],
    },
  },
  legal: {
    metaTitle: "Mentions légales",
    metaDescription: "Mentions légales du site MH Group : éditeur, hébergement, propriété intellectuelle et responsabilité.",
    label: "Informations légales",
    h1: "Mentions légales",
    updated: "Dernière mise à jour",
    toComplete: "À compléter",
    sections: {
      publisher: "Éditeur du site",
      publisherLines: ["Raison sociale", "Forme juridique", "Adresse", "ICE", "RC", "Directeur de la publication", "E-mail"],
      hosting: "Hébergement",
      hostingText: "Le site est hébergé par Vercel Inc., 440 N Barranca Ave #4133, Covina, CA 91723, États-Unis — vercel.com.",
      ip: "Propriété intellectuelle",
      ipText: "L'ensemble des contenus de ce site (textes, visuels, logo, code) est la propriété de {name}, sauf mention contraire. Toute reproduction sans autorisation écrite préalable est interdite.",
      liability: "Responsabilité",
      liabilityText: "{name} s'efforce de fournir des informations exactes et à jour, mais ne peut garantir l'absence d'erreurs. Les liens vers des sites tiers n'engagent pas sa responsabilité.",
      data: "Données personnelles",
      dataText: "Le traitement de vos données personnelles est décrit dans notre politique de confidentialité.",
    },
  },
  privacy: {
    metaTitle: "Politique de confidentialité",
    metaDescription:
      "Comment MH Group collecte et protège vos données personnelles, conformément à la loi marocaine n° 09-08 relative à la protection des données personnelles.",
    label: "Informations légales",
    h1: "Politique de confidentialité",
    intro:
      "{name} accorde une grande importance à la protection de vos données personnelles. Cette politique explique quelles données nous collectons, pourquoi, et quels sont vos droits, conformément à la loi n° 09-08 relative à la protection des personnes physiques à l'égard du traitement des données à caractère personnel.",
    sections: [
      {
        title: "Données collectées",
        text: "Lorsque vous utilisez le formulaire de contact ou nous écrivez, nous recueillons les informations que vous nous transmettez : nom, adresse e-mail, entreprise, service souhaité, budget indicatif et message.",
      },
      {
        title: "Finalité",
        text: "Ces données servent uniquement à répondre à votre demande, à préparer un devis et à assurer le suivi de notre relation commerciale. Elles ne sont jamais vendues ni cédées à des tiers.",
      },
      {
        title: "Mesure d'audience",
        text: "Nous utilisons Vercel Web Analytics pour mesurer la fréquentation du site de manière agrégée et anonyme. Cet outil ne dépose pas de cookie et ne permet pas de vous identifier.",
      },
      {
        title: "Destinataires et hébergement",
        text: "Les données sont traitées par {name} et par nos prestataires techniques, uniquement pour les besoins du service : hébergement du site (Vercel) et envoi des e-mails du formulaire.",
      },
      {
        title: "Durée de conservation",
        text: "Les demandes de contact sont conservées pendant la durée nécessaire au traitement de votre demande puis, le cas échéant, pendant la durée de la relation commerciale.",
      },
      {
        title: "Vos droits",
        text: "Vous disposez d'un droit d'accès, de rectification et d'opposition au traitement de vos données. Pour l'exercer, écrivez-nous à {email}. Vous pouvez également adresser une réclamation à la CNDP (Commission Nationale de contrôle de la protection des Données à caractère Personnel) — cndp.ma.",
      },
    ],
  },
  notFound: {
    title: "Page introuvable",
    text: "La page que vous cherchez n'existe pas ou a été déplacée.",
    back: "Retour à l'accueil",
  },
};

export type Dictionary = typeof fr;
